const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let dashboardData=null,localEntries=[],adminLoaded=false,toastTimer;
const token=()=>sessionStorage.getItem("luminaToken")||"";
function showToast(message,error=false){const el=$("#toast");el.textContent=message;el.className=`toast show${error?" error":""}`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.className="toast",3200)}
function adminHeaders(){const h={"X-Lumina-Admin":"1"};if(token())h["X-Lumina-Token"]=token();return h}
async function request(url,options={}){const response=await fetch(url,{cache:"no-store",...options});let body={};try{body=await response.json()}catch{}if(!response.ok){const err=new Error(body.error||`${response.status} ${response.statusText}`);err.status=response.status;throw err}return body}
async function adminRequest(url,options={}){return request(url,{...options,headers:{...adminHeaders(),...(options.headers||{})}})}
function formatDate(value){if(!value)return"等待首次扫描";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString("zh-CN",{hour12:false})}
function latencyClass(ms){return ms>5000?"bad":ms>1800?"slow":""}
function renderDashboard(data){dashboardData=data;const state=$("#liveState");state.className=`state-pill ${data.refreshing?"refreshing":data.ok?"online":"error"}`;state.querySelector("span").textContent=data.refreshing?"检测中":data.ok?"运行正常":"需要检查";$("#healthValue").textContent=`${data.healthPercent}%`;$("#healthRing").style.setProperty("--p",data.healthPercent);$("#channelCount").textContent=`${data.published} / ${data.requested}`;$("#updatedAt").textContent=formatDate(data.updatedAt);$("#averageLatency").textContent=data.averageValidationMs==null?"--":`${data.averageValidationMs} ms`;$("#p95Latency").textContent=data.p95ValidationMs==null?"--":`${data.p95ValidationMs} ms`;$("#scanElapsed").textContent=data.elapsedSeconds==null?"--":`${data.elapsedSeconds} s`;$("#scanState").textContent=data.error?`上次错误：${data.error}`:data.refreshing?"正在重新检测全部频道":data.state==="ready"?"最近一次扫描已完成":"等待生成播放列表";const groups=[...new Set(data.channels.map(x=>x.group))];const select=$("#groupFilter"),selected=select.value;select.innerHTML='<option value="">全部分组</option>'+groups.map(x=>`<option>${escapeHtml(x)}</option>`).join("");select.value=selected;filterChannels()}
function escapeHtml(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function filterChannels(){if(!dashboardData)return;const q=$("#channelSearch").value.trim().toLowerCase(),group=$("#groupFilter").value,health=$("#healthFilter").value;const rows=dashboardData.channels.filter(c=>(!q||`${c.name} ${c.upstreamHost||""}`.toLowerCase().includes(q))&&(!group||c.group===group)&&(!health||(health==="online")===c.online));$("#channelRows").innerHTML=rows.length?rows.map(c=>{const ms=c.validationMs;return `<tr><td><span class="channel-name">${escapeHtml(c.name)}</span><div class="muted">${escapeHtml(c.id)}</div></td><td>${escapeHtml(c.group)}</td><td><span class="health ${c.online?"online":"offline"}"><i></i>${c.online?"在线":"未通过"}</span></td><td>${ms==null?'<span class="muted">--</span>':`<span class="latency ${latencyClass(ms)}"><span class="latency-bar"><i></i></span>${ms} ms</span>`}</td><td class="muted">${escapeHtml(c.upstreamHost||"—")}</td></tr>`}).join(""):'<tr><td colspan="5" class="empty">没有符合筛选条件的频道</td></tr>'}
async function loadDashboard(){try{renderDashboard(await request("/api/dashboard"))}catch(e){showToast(`状态读取失败：${e.message}`,true)}}
function showTokenDialog(){$("#tokenInput").value=token();$("#tokenDialog").classList.remove("hidden");setTimeout(()=>$("#tokenInput").focus(),30)}
function handleAdminError(e){if(e.status===401){showTokenDialog();showToast("管理令牌不正确或尚未填写",true)}else if(e.status===403){$("#adminNotice").textContent="管理写操作默认仅允许局域网访问。如果经过反向代理，请设置 ADMIN_TOKEN，并确保代理传递真实客户端地址。";$("#adminNotice").classList.remove("hidden");showToast("当前连接没有管理权限",true)}else showToast(e.message,true)}
function sourceRow(value=""){const row=document.createElement("div");row.className="source-row";row.innerHTML=`<span></span><input type="url" value="${escapeHtml(value)}" placeholder="https://example.com/playlist.m3u"><button class="row-delete" title="删除">×</button>`;row.querySelector("button").onclick=()=>{row.remove();numberSources()};$("#sourceList").append(row);numberSources()}
function numberSources(){$$(".source-row span").forEach((el,i)=>el.textContent=i+1)}
function renderLocalEntries(){const body=$("#localRows");body.innerHTML=localEntries.length?localEntries.map((e,i)=>`<tr data-index="${i}"><td><input data-field="name" value="${escapeHtml(e.name)}"></td><td><input data-field="group" value="${escapeHtml(e.group)}"></td><td><input data-field="url" type="url" value="${escapeHtml(e.url)}"></td><td><button class="row-delete" data-delete="${i}">×</button></td></tr>`).join(""):'<tr><td colspan="4" class="empty">暂时没有本地自定义频道</td></tr>';$$('[data-delete]').forEach(b=>b.onclick=()=>{localEntries.splice(Number(b.dataset.delete),1);renderLocalEntries();syncRaw()});$$('#localRows input').forEach(input=>input.onchange=()=>{const i=Number(input.closest("tr").dataset.index);localEntries[i][input.dataset.field]=input.value.trim();syncRaw()})}
function buildM3u(){return "#EXTM3U\n"+localEntries.filter(x=>x.name&&x.url).map(x=>`#EXTINF:-1 tvg-name="${x.name.replaceAll('"','')}" group-title="${(x.group||"自定义").replaceAll('"','')}",${x.name}\n${x.url}`).join("\n")+(localEntries.length?"\n":"")}
function syncRaw(){$("#rawM3u").value=buildM3u()}
function parseRaw(text){const result=[];let info="";for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(line.startsWith("#EXTINF")){info=line;continue}if(info&&/^https?:\/\//i.test(line)){const name=(info.match(/tvg-name="([^"]*)"/)||[])[1]||info.split(",").pop().trim(),group=(info.match(/group-title="([^"]*)"/)||[])[1]||"自定义";result.push({name,group,url:line});info=""}}return result}
async function loadAdmin(){try{const data=await adminRequest("/api/local-m3u"),dash=dashboardData||await request("/api/dashboard");localEntries=data.entries;$("#rawM3u").value=data.content;renderLocalEntries();$("#sourceList").innerHTML="";dash.sources.configured.forEach(sourceRow);if(!dash.sources.configured.length)sourceRow();if(dash.sources.environment.length){$("#envSources").classList.remove("hidden");$("#envSources div").textContent=dash.sources.environment.join("\n")}adminLoaded=true;$("#adminNotice").classList.add("hidden")}catch(e){handleAdminError(e)}}
async function saveSources(){const sources=$$("#sourceList input").map(x=>x.value.trim()).filter(Boolean);return adminRequest("/api/source-playlists",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({sources})})}
async function saveLocal(){const content=$("#rawM3u").value;const result=await adminRequest("/api/local-m3u",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({content})});localEntries=result.entries;renderLocalEntries();return result}
async function queueRefresh(){try{await adminRequest("/api/refresh",{method:"POST"});showToast("已提交重新检测任务");setTimeout(loadDashboard,1600)}catch(e){handleAdminError(e)}}
$$('.tab').forEach(tab=>tab.onclick=()=>{$$('.tab').forEach(x=>x.classList.toggle("active",x===tab));$$('.view').forEach(x=>x.classList.remove("active"));$(`#${tab.dataset.tab}View`).classList.add("active");if(tab.dataset.tab==="sources"&&!adminLoaded)loadAdmin()});
[$("#channelSearch"),$("#groupFilter"),$("#healthFilter")].forEach(x=>x.addEventListener("input",filterChannels));
$("#refreshButton").onclick=queueRefresh;$("#copyButton").onclick=async()=>{const url=`${location.origin}/live/yangshi.m3u`;try{await navigator.clipboard.writeText(url);showToast("订阅地址已复制")}catch{showToast(url)}};$("#tokenButton").onclick=showTokenDialog;$("#closeDialog").onclick=()=>$("#tokenDialog").classList.add("hidden");$("#saveToken").onclick=()=>{sessionStorage.setItem("luminaToken",$("#tokenInput").value.trim());$("#tokenDialog").classList.add("hidden");adminLoaded=false;loadAdmin()};$("#tokenDialog").onclick=e=>{if(e.target===$("#tokenDialog"))$("#tokenDialog").classList.add("hidden")};
$("#addSourceButton").onclick=()=>sourceRow();$("#entryForm").onsubmit=e=>{e.preventDefault();localEntries.push({name:$("#entryName").value.trim(),group:$("#entryGroup").value.trim()||"自定义",url:$("#entryUrl").value.trim()});e.target.reset();renderLocalEntries();syncRaw()};$("#saveLocalButton").onclick=async()=>{try{await saveLocal();showToast("本地 M3U 已保存")}catch(e){handleAdminError(e)}};$("#deleteLocalButton").onclick=async()=>{if(!confirm("确定清空 config/local.m3u 吗？"))return;try{await adminRequest("/api/local-m3u",{method:"DELETE"});localEntries=[];syncRaw();renderLocalEntries();showToast("本地 M3U 已清空")}catch(e){handleAdminError(e)}};$("#rawM3u").onchange=()=>{localEntries=parseRaw($("#rawM3u").value);renderLocalEntries()};$("#sourceRefreshButton").onclick=async()=>{try{await Promise.all([saveSources(),saveLocal()]);await adminRequest("/api/refresh",{method:"POST"});showToast("来源已保存，重新检测任务已提交");setTimeout(loadDashboard,1600)}catch(e){handleAdminError(e)}};
loadDashboard();setInterval(loadDashboard,15000);
